stages :
  - test
  - build

test-project:
  stage: test
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make cmake g++
    - mkdir -p $HOME/.local
    - curl -s "https://cmake.org/files/v3.26/cmake-3.26.0-linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C $HOME/.local
    - export PATH=$HOME/.local/bin:$PATH
  script:
    - mkdir build_tests
    - cd build_tests
    - cmake ../tests && cmake --build . && make
    - ./TMSE_tests --gtest_output="xml:report.xml"
  when: always
  artifacts:
    reports:
      junit: tests/report.xml

build-project:
  stage: build
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make cmake g++
    - mkdir -p $HOME/.local
    - curl -s "https://cmake.org/files/v3.26/cmake-3.26.0-linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C $HOME/.local
    - export PATH=$HOME/.local/bin:$PATH
  script:
    - mkdir build
    - cd build
    - cmake .. && cmake --build . && make
  artifacts:
    paths:
      - build/TMSE

